### ISSUE TITLE
推理的掩码_时间嵌入疑问

### ISSUE THREAD

**Issue by Anivie** [Aimol-l/OrtInference#12]
您好，我还在继续尝试复现您的代码，目前在最后一个部分卡了很久还是解决不了，抱歉只能再打扰一下您

在memory_attention的输入比较复杂，不熟悉cpp所以不太理解代码中的内容，请问我这样的理解是否正确？如果存在错误的话烦请指正

memory_attention存在五个输入：
- "current_vision_feat"：直接来源于image_encoder_output["vision_feats"]
- "current_vision_pos_embed"：直接来源于image_encoder_output["vision_pos_embed"]
- "memory_0", input_type: 来源于推理历史中的image_decoder_output["obj_ptr"]，只需要简单的拼接就可以，大小可以堆叠到16 (16, 256)
- "memory_1", input_type: 来源于推理历史中的memory_encoder_output["maskmem_features"]，只需要简单的拼接就可以，大小可以堆叠到7 (7, 64, 64, 64)
- "memory_pos_embed"：最复杂的一个

来源两个部分，`memory_encoder_output["maskmem_pos_enc"]`和`memory_encoder_output["temporal_code"]`，前者要保存历史中的所有`maskmem_pos_enc`为`maskmem_pos_enc_array`，上限为7，后者只需要保存一份，一份中存在七个编码，取出其中的每一份编码与maskmem_pos_enc_array的一个成员相加（如果当前是第二帧，则只有一份maskmem_pos_enc，用temporal_code的第一组数据相加，后续的都扔掉）
相加的结果拼接上4 * 帧数量个`0值`就可以成为最终的结果(4096 * maskmem_pos_enc_array大小 + 4 * 帧数量)

我目前比较疑惑的部分是temporal_code的理解是否正确，一份temporal_code就是提供了七帧使用的量吗？第二个部分是[源码中](https://github.com/Aimol-l/OrtInference/blob/5cf4fea91064e782fc9b21ac6b07d3ee29369889/src/SAM2.cpp#L422)的`4*std::min(infer_status.current_frame,16)`这个部分，实在没有找到这部分是在哪里填充的，猜测可能是全为0？

目前我推理出的结果坐标大致准确，但是掩码不知道为什么会乱掉，我猜是掩码嵌入那部分的理解有误？希望能得到您的建议
![18540fee5052f110055c906b032916d4](https://github.com/user-attachments/assets/fa88b54a-1b81-47fa-8ad1-e39253f2697f)

**Comment by Anivie** [comment]
不知道什么原因今天突然自己好了。。。我甚至没有动过它( ﾉ ﾟｰﾟ)ﾉ

不过还是保留这个issue等待一下作者回复吧，我也不确定我的理解是否是正确的，目前我的memory_pos_embed按如下格式拼接：
```
0000 maskmem_pos_enc_array[0](4096, 1, 64) + temporal_code[0](1, 1, 64)
0000 maskmem_pos_enc_array[1](4096, 1, 64) + temporal_code[1](1, 1, 64)
...
```

![image](https://github.com/user-attachments/assets/fab22f21-767f-42ed-8ab2-6d24bf30e9a5)

**Comment by weiyaokun** [comment]
> 不知道什么原因今天突然自己好了。。。我甚至没有动过它( ﾉ ﾟｰﾟ)ﾉ
> 
> 不过还是保留这个issue等待一下作者回复吧，我也不确定我的理解是否是正确的，目前我的memory_pos_embed按如下格式拼接：
> 
> ```
> 0000 maskmem_pos_enc_array[0](shape=[4096, 1, 64]) + temporal_code[0](shape=[1, 1, 64])
> 0000 maskmem_pos_enc_array[1](shape=[4096, 1, 64]) + temporal_code[1](shape=[1, 1, 64])
> ...
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/88354708/387502786-fab22f21-767f-42ed-8ab2-6d24bf30e9a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTYyODUsIm5iZiI6MTczMzgxNTk4NSwicGF0aCI6Ii84ODM1NDcwOC8zODc1MDI3ODYtZmFiMjJmMjEtNzY3Zi00MmVkLThhYjItNmQyNGJmMzBlOWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA3MzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMzdmNTUwMDM0ZmYxYWVjMjhhZDFjMTEzMTliMjVmMTQ5OWIzZjZhZDU1ZjBhYmZmYzhjYzIwMTk4MDI4YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kgwAgJ8yHcM9PFa8aSFFf-2uYBsfDdWwHr5r3pmYxgM)

请问您是怎么输出好几个目标呢？是添加多个点吗？

**Comment by Anivie** [comment]
> > 不知道什么原因今天突然自己好了。。。我甚至没有动过它( ﾉ ﾟｰﾟ)ﾉ
> > 不过还是保留这个issue等待一下作者回复吧，我也不确定我的理解是否是正确的，目前我的memory_pos_embed按如下格式拼接：
> > ```
> > 0000 maskmem_pos_enc_array[0](shape=[4096, 1, 64]) + temporal_code[0](shape=[1, 1, 64])
> > 0000 maskmem_pos_enc_array[1](shape=[4096, 1, 64]) + temporal_code[1](shape=[1, 1, 64])
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/88354708/387502786-fab22f21-767f-42ed-8ab2-6d24bf30e9a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTYyODUsIm5iZiI6MTczMzgxNTk4NSwicGF0aCI6Ii84ODM1NDcwOC8zODc1MDI3ODYtZmFiMjJmMjEtNzY3Zi00MmVkLThhYjItNmQyNGJmMzBlOWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA3MzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMzdmNTUwMDM0ZmYxYWVjMjhhZDFjMTEzMTliMjVmMTQ5OWIzZjZhZDU1ZjBhYmZmYzhjYzIwMTk4MDI4YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kgwAgJ8yHcM9PFa8aSFFf-2uYBsfDdWwHr5r3pmYxgM)
> 
> 请问您是怎么输出好几个目标呢？是添加多个点吗？

并行的decode，每次decode都传入一个点
