### ISSUE TITLE
onnxruntime环境配置问题

### ISSUE THREAD

**Issue by UraLee** [Aimol-l/OrtInference#3]
想问问onnxruntime环境怎么配，我这边用pip加上指定路径，结果报缺onnxruntimeConfig.cmake
![屏幕截图 2024-10-05 155755](https://github.com/user-attachments/assets/fa6e49e0-fc5f-40d2-accc-e0c77ae17b5e)

**Comment by Aimol-l** [comment]
> 想问问onnxruntime环境怎么配，我这边用pip加上指定路径，结果报缺onnxruntimeConfig.cmake
> ![屏幕截图 2024-10-05 155755](https://github.com/user-attachments/assets/fa6e49e0-fc5f-40d2-accc-e0c77ae17b5e)
> 

这个问题不应该在这里提出，你应该先学习cmake的使用。
主要问题是find_package的搜索路径中没找到ort相关的文件，把ort的相关.cmake添加到搜索路径上。
